
CREATE DATABASE IF NOT EXISTS testport;


USE testport;


CREATE TABLE IF NOT EXISTS usersrate (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    rate INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

